# Generated by Django 4.2 on 2023-05-12 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BacSi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bacsi',
            old_name='PhongKham',
            new_name='PhongKham_id',
        ),
    ]
