# Generated by Django 4.2 on 2023-05-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BacSi', '0002_rename_phongkham_bacsi_phongkham_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bacsi',
            name='id',
        ),
        migrations.AlterField(
            model_name='bacsi',
            name='BacSi_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
