# Generated by Django 4.2 on 2023-05-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LoaiKham', '0001_initial'),
        ('BacSi', '0003_remove_bacsi_id_alter_bacsi_bacsi_id'),
        ('PhongKham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenhNhan',
            fields=[
                ('BenhNhan_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('BSPhuTrach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BacSi.bacsi')),
                ('LoaiKham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoaiKham.loaikham')),
                ('PhongKham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhongKham.phongkham')),
            ],
        ),
    ]
