# Generated by Django 4.2 on 2023-05-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BenhNhan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benhnhan',
            old_name='LoaiKham',
            new_name='LoaiKham_id',
        ),
        migrations.RenameField(
            model_name='benhnhan',
            old_name='PhongKham',
            new_name='PhongKham_id',
        ),
    ]
